n = input('Digite algo: ')
print('O tipo primitivo é ', type(n))
print('É númerico? ', n.isnumeric())
print('É alfabetico? ', n.isalpha())
print('Está em minuscula? ', n.islower())
print('Está maiusculo? ', n.isupper())
