campeonato = ('botafogo', 'palmeiras', 'fluminense', 'cruzeiro', 'athletico-pr', 'atletico-mg', 'santos', 'fortaleza', 'flamengo', 'são paulo', 'grêmio', 'internacional', 'bragantino', 'bahia', 'goiás', 'vasco', 'corinthians', 'cuiaba', 'coritiba', 'américa-mg')
print('\033[1;31m-=\033[m' * 25)
print(f'A lista dos times é: {campeonato}')
print('\033[1;31m-=\033[m' * 25)
print(f'Os cincos primeiros são: {campeonato[:5]}')
print('\033[1;31m-=\033[m' * 25)
print(f'Os 4 ultimos colocados são: {campeonato[16:]}')
print('\033[1;31m-=\033[m' * 25)
print(f'Em ordem alfabetica são: {sorted(campeonato)}')
print('\033[1;31m-=\033[m' * 25)
print(f'O corinthians está na {campeonato.index("corinthians")+1}ª posição')
print('\033[1;31m-=\033[m' * 25)
